import { strToU8,zipSync } from 'fflate';
import { Operations,monthTotals,chargeTotals,chargeStatus,seoulLocal } from './operations-model';
const esc=(s:unknown)=>String(s??'').replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F]/g,'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const col=(n:number)=>{let s='';for(n++;n;n=Math.floor((n-1)/26))s=String.fromCharCode(65+(n-1)%26)+s;return s;};
function sheet(rows:(string|number)[][]){return `<?xml version="1.0" encoding="UTF-8"?><worksheet xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main"><cols>${(rows[0]||[]).map((_,n)=>`<col min="${n+1}" max="${n+1}" width="24" customWidth="1"/>`).join('')}</cols><sheetData>${rows.map((r,n)=>`<row r="${n+1}">${r.map((v,c)=>typeof v==='number'?`<c r="${col(c)}${n+1}"><v>${v}</v></c>`:`<c r="${col(c)}${n+1}" t="inlineStr"><is><t xml:space="preserve">${esc(v)}</t></is></c>`).join('')}</row>`).join('')}</sheetData></worksheet>`;}
export function operationsWorkbook(data:Operations,month:string){const t=monthTotals(data,month);const sheets:{name:string;rows:(string|number)[][]}[]=[{name:'월별 현황',rows:[['항목','금액 또는 건수'],['기준 월',month],['이번 달 입금',t.received],['이번 달 환불',t.refunded],['이번 달 받은 금액 (환불 제외)',t.net],['이번 달 지출',t.spent],['수입·지출 차액',t.balance],['전체 미수납',t.due],['전체 미수납 건수',t.unpaidCount]]},{name:'월 일정',rows:[['내담자','종류','시작 (한국 시간)','소요 분','상태','결제 항목 ID','메모'],...data.appointments.filter(r=>seoulLocal(r.data.startAt!).startsWith(month)).map(({data:d})=>[d.clientName||'',d.kind||'',seoulLocal(d.startAt!).replace('T',' '),d.duration||60,d.status||'',d.chargeId||'',d.memo])]},{name:'전체 결제 항목',rows:[['결제 ID','등록일','내담자','항목','받을 금액','누적 입금','누적 환불','보유 금액','미수납','상태','메모'],...data.charges.map(({id,data:d})=>{const t=chargeTotals(d);return [id,d.date||'',d.clientName||'',d.title,d.amount||0,t.received,t.refunded,t.net,t.due,chargeStatus(d),d.memo];})]},{name:'월 입출금',rows:[['결제 ID','내담자','항목','입출금 ID','날짜','구분','금액','방법','증빙','메모','기록 상태'],...data.charges.flatMap(({id,data:d})=>(d.payments||[]).filter(p=>p.date.startsWith(month)).map(p=>[id,d.clientName||'',d.title,p.id,p.date,p.direction==='receipt'?'입금':'환불',p.amount,p.method,p.evidence,p.memo,p.voided?'정정 (집계 제외)':'유효']))]},{name:'월 지출',rows:[['날짜','항목','분류','금액','메모','영수증 파일 수','기록 상태'],...data.expenses.filter(r=>r.data.date?.startsWith(month)).map(({data:d})=>[d.date||'',d.title,d.category||'',d.amount||0,d.memo,d.attachments?.length||0,d.archived?'취소 (집계 제외)':'유효'])]}];
 const files:Record<string,Uint8Array>={};files['[Content_Types].xml']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/xl/workbook.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet.main+xml"/>${sheets.map((_,n)=>`<Override PartName="/xl/worksheets/sheet${n+1}.xml" ContentType="application/vnd.openxmlformats-officedocument.spreadsheetml.worksheet+xml"/>`).join('')}</Types>`);files['_rels/.rels']=strToU8('<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="xl/workbook.xml"/></Relationships>');files['xl/workbook.xml']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><workbook xmlns="http://schemas.openxmlformats.org/spreadsheetml/2006/main" xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships"><sheets>${sheets.map((s,n)=>`<sheet name="${esc(s.name)}" sheetId="${n+1}" r:id="rId${n+1}"/>`).join('')}</sheets></workbook>`);files['xl/_rels/workbook.xml.rels']=strToU8(`<?xml version="1.0" encoding="UTF-8"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships">${sheets.map((_,n)=>`<Relationship Id="rId${n+1}" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/worksheet" Target="worksheets/sheet${n+1}.xml"/>`).join('')}</Relationships>`);sheets.forEach((s,n)=>files[`xl/worksheets/sheet${n+1}.xml`]=strToU8(sheet(s.rows)));return zipSync(files,{level:6});
}
export function downloadOperations(data:Operations,month:string){const bytes=operationsWorkbook(data,month),url=URL.createObjectURL(new Blob([new Uint8Array(bytes)],{type:'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet'}));const a=document.createElement('a');a.href=url;a.download=`AUDE_운영기록_${month}.xlsx`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
