export type ReportData = { clientName: string; testName: string; date: string; interpretationDate: string; scores: string; deliveryText: string; reaction: string };
const escape = (value: string) => value.replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]!));
export function assessmentReport(data: ReportData, seal: string) {
  const title = '심리검사 해석보고서';
  const section = (heading: string, body: string) => `<section><h2>${heading}</h2><div class="content">${escape(body || '작성된 내용이 없습니다.')}</div></section>`;
  return `<!doctype html><html lang="ko"><head><meta charset="utf-8"><title>${escape(data.clientName)}_${title}</title><style>
  @page{size:A4;margin:20mm 19mm}*{box-sizing:border-box}body{margin:0;background:#fff;color:#282923;font-family:'Malgun Gothic','Apple SD Gothic Neo',sans-serif;font-size:11pt;line-height:1.8;padding:24px}header{border-top:3px solid #465244;padding-top:22px;margin-bottom:30px}.brand{font-size:10pt;letter-spacing:3px;color:#62715e}h1{font-size:23pt;line-height:1.4;margin:12px 0}.tag{font-size:10pt;color:#687164}dl{display:grid;grid-template-columns:100px 1fr;border-top:1px solid #ddd;border-bottom:1px solid #ddd;padding:12px 0;margin:22px 0}dt{color:#6b6b63}dd{margin:0;overflow-wrap:anywhere}h2{font-size:13pt;border-bottom:1px solid #ddd;padding-bottom:8px;break-after:avoid}section{margin:28px 0}.content{white-space:pre-wrap;overflow-wrap:anywhere;orphans:3;widows:3}footer{margin-top:40px;border-top:1px solid #ddd;padding-top:18px;break-inside:avoid}.sign{display:flex;align-items:center;justify-content:flex-end;gap:16px;font-size:14pt;font-weight:700}.sign img{width:65px;height:65px;object-fit:contain}.footnote{font-size:9pt;color:#777;margin-top:18px}@media print{body{padding:0}header,dl{break-inside:avoid}*{-webkit-print-color-adjust:exact;print-color-adjust:exact}}
  </style></head><body><header><div class="brand">AUDE COUNSELING</div><h1>${title}</h1><div class="tag">내담자 전달용</div></header><dl><dt>이름</dt><dd>${escape(data.clientName)}</dd><dt>검사명</dt><dd>${escape(data.testName)}</dd><dt>실시일</dt><dd>${escape(data.date || '미정')}</dd><dt>해석상담일</dt><dd>${escape(data.interpretationDate || '미정')}</dd></dl>${section('심리검사 해석', data.deliveryText)}<footer><div class="sign"><span>아우데 심리상담센터</span><img src="${seal}" alt="아우데 심리상담센터 직인"></div><div class="footnote">본 보고서는 검사 결과와 해석상담을 바탕으로 작성되었습니다.</div></footer></body></html>`;
}
