'use client';
import Link from 'next/link';
import { FormEvent,useEffect,useRef,useState } from 'react';
import { OperationRow,OperationType,Operations,appointmentKinds,appointmentStatuses,paymentMethods,evidenceStatuses,expenseCategories,seoulDate,seoulLocal,won,chargeTotals,chargeStatus,monthTotals,overlaps } from '../lib/operations-model';
import { downloadOperations } from '../lib/operations-export';
import './operations.css';
type Client={id:string;name:string;clientCode:string};
async function api(method='GET',body?:unknown){const r=await fetch('/api/admin/operations',{method,cache:'no-store',...(body?{headers:{'Content-Type':'application/json'},body:JSON.stringify(body)}:{})});const data=await r.json();if(!r.ok)throw new Error(data.error||'저장하지 못했습니다.');return data;}
export default function OperationsWorkspace({mode}:{mode:'calendar'|'finance'}){
 const [data,setData]=useState<Operations>({appointments:[],charges:[],expenses:[]});const [clients,setClients]=useState<Client[]>([]);const [loading,setLoading]=useState(true);const [ready,setReady]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const [month,setMonth]=useState(seoulDate().slice(0,7));const [day,setDay]=useState(seoulDate());const [calendarView,setCalendarView]=useState<'month'|'week'|'today'>('month');const [tab,setTab]=useState<'charges'|'expenses'>('charges');const [filter,setFilter]=useState('전체');const [query,setQuery]=useState('');const [clientFilter,setClientFilter]=useState('');const [editing,setEditing]=useState<{type:OperationType;row?:OperationRow;start?:string}|null>(null);const [detail,setDetail]=useState<OperationRow|null>(null);const [busy,setBusy]=useState(false);
 async function load(){const [operations,r]=await Promise.all([api(),fetch('/api/admin/clients',{cache:'no-store'})]);if(!r.ok)throw new Error(r.status===401?'관리자 로그인 후 이용해 주세요.':'내담자 목록을 불러오지 못했습니다.');setData(operations);setClients(await r.json());setReady(true);}
 useEffect(()=>{load().catch(e=>setError(e.message)).finally(()=>setLoading(false));setClientFilter(new URLSearchParams(location.search).get('client')||'');},[]);
 function replace(row:OperationRow){const key=row.data.type==='aude-appointment'?'appointments':row.data.type==='aude-charge'?'charges':'expenses';setData(d=>({...d,[key]:d[key].some(r=>r.id===row.id)?d[key].map(r=>r.id===row.id?row:r):[row,...d[key]]}));setDetail(d=>d?.id===row.id?row:d);}
 async function mutate(row:OperationRow,action:string,fields:object={}){setBusy(true);setError('');try{const updated=await api('PATCH',{id:row.id,version:row.data.version,action,...fields});replace(updated);setNotice('변경사항을 저장했습니다.');}catch(e){setError((e as Error).message);throw e;}finally{setBusy(false);}}
 const totals=monthTotals(data,month);const calendarItems=data.appointments.filter(r=>!clientFilter||r.data.clientId===clientFilter).sort((a,b)=>a.data.startAt!.localeCompare(b.data.startAt!));
 const chargeList=data.charges.filter(r=>(!clientFilter||r.data.clientId===clientFilter)&&(!query||[r.data.clientName,r.data.title].some(v=>v?.includes(query)))&&(filter==='전체'||chargeStatus(r.data)===filter));const expenseList=data.expenses.filter(r=>r.data.date?.startsWith(month)&&(!query||[r.data.title,r.data.category].some(v=>v?.includes(query))));
 const weekdays=['일','월','화','수','목','금','토'];const first=new Date(month+'-01T00:00:00Z'),last=new Date(Date.UTC(first.getUTCFullYear(),first.getUTCMonth()+1,0)).getUTCDate(),offset=first.getUTCDay();const cells=Array.from({length:Math.ceil((offset+last)/7)*7},(_,n)=>n-offset+1).map(n=>n>0&&n<=last?month+'-'+String(n).padStart(2,'0'):null);
 function moveMonth(n:number){const d=new Date(month+'-01T00:00:00Z');d.setUTCMonth(d.getUTCMonth()+n);setMonth(d.toISOString().slice(0,7));setDay(d.toISOString().slice(0,10));}
 const weekStart=new Date(day+'T00:00:00Z');weekStart.setUTCDate(weekStart.getUTCDate()-weekStart.getUTCDay());const weekDays=Array.from({length:7},(_,n)=>{const d=new Date(weekStart);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10);});const shownDays=calendarView==='today'?[seoulDate()]:weekDays;
 const appointmentsForDay=(date:string)=>calendarItems.filter(r=>seoulDate(r.data.startAt!)===date);
 return <main className="adminShell opsWorkspace"><header className="adminHeader workspaceHeader"><div><Link className="adminBrand" href="/admin">AUDE</Link><span>통합 관리</span></div><nav><Link href="/admin">접수</Link><Link href="/admin/clients">내담자</Link><Link href="/admin/assessments">투사검사</Link><Link className={mode==='calendar'?'active':''} href="/admin/calendar">일정</Link><Link className={mode==='finance'?'active':''} href="/admin/finance">수납·지출</Link></nav><Link className="adminHomeLink" href="/" target="_blank" rel="noopener noreferrer">홈페이지 보기 ↗</Link></header>
 <section className="adminDashboard workspacePage"><div className="opsHeading"><div><p className="sectionNumber">AUDE · PRIVATE OFFICE</p><h1>{mode==='calendar'?'상담 일정':'수납·지출'}</h1><p>{mode==='calendar'?'상담과 검사 일정을 내담자 기록에 연결합니다.':'입금일을 기준으로 받은 금액과 지출을 정리합니다.'}</p></div><button className="opsPrimary" disabled={loading||busy||!ready} onClick={()=>setEditing({type:mode==='calendar'?'aude-appointment':tab==='charges'?'aude-charge':'aude-expense',start:day+'T19:00'})}>{mode==='calendar'?'+ 일정 등록':tab==='charges'?'+ 결제 항목 등록':'+ 지출 등록'}</button></div>
 {error&&<p className="opsError" role="alert">{error}</p>}{notice&&<p className="opsNotice" role="status">{notice}</p>}{loading?<p>운영 기록을 불러오는 중…</p>:!ready?<div className="opsEmpty"><Link href="/admin">접수 화면에서 관리자 로그인하기 ↗</Link><button onClick={()=>load().then(()=>setError('')).catch(e=>setError(e.message))}>다시 불러오기</button></div>:<>
 <div className="opsToolbar"><div className="opsMonth"><button aria-label="이전 달" onClick={()=>moveMonth(-1)}>←</button><input type="month" aria-label="기준 월" value={month} min="2000-01" max="2100-12" onChange={e=>{if(e.target.value){setMonth(e.target.value);setDay(e.target.value+'-01');}}}/><button aria-label="다음 달" onClick={()=>moveMonth(1)}>→</button><button onClick={()=>{setMonth(seoulDate().slice(0,7));setDay(seoulDate());}}>오늘</button></div><select aria-label="내담자 필터" value={clientFilter} onChange={e=>setClientFilter(e.target.value)}><option value="">모든 내담자</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.clientCode}</option>)}</select><button onClick={()=>downloadOperations(data,month)}>엑셀 내려받기</button><button disabled={busy} onClick={()=>load().then(()=>setNotice('목록을 새로 불러왔습니다.')).catch(e=>setError(e.message))}>새로고침</button></div>
 <div className="opsStats"><div><span>오늘 일정</span><strong>{data.appointments.filter(r=>r.data.status==='예약'&&seoulDate(r.data.startAt!)===seoulDate()).length}<small>건</small></strong></div><div><span>이번 달 받은 금액 · 환불 제외</span><strong>{won(totals.net)}</strong><small>입금 {won(totals.received)} · 환불 {won(totals.refunded)}</small></div><div><span>전체 미수납 · {totals.unpaidCount}건</span><strong>{won(totals.due)}</strong></div><div><span>이번 달 지출</span><strong>{won(totals.spent)}</strong></div><div><span>수입·지출 차액</span><strong>{won(totals.balance)}</strong></div></div>
 {mode==='calendar'?<><div className="opsToolbar"><div className="opsTabs">{(['month','week','today'] as const).map(v=><button key={v} aria-pressed={calendarView===v} className={calendarView===v?'active':''} onClick={()=>setCalendarView(v)}>{v==='month'?'월간':v==='week'?'주간':'오늘'}</button>)}</div><span>한국 시간 · 일정 클릭 시 상세 확인</span></div>
 {calendarView==='month'?<div className="opsCalendar">{weekdays.map(w=><div key={w} className="opsWeekday">{w}</div>)}{cells.map((date,n)=><div key={date||'blank'+n} className={'opsDay '+(date===day?'selected ':'')+(date===seoulDate()?'today':'')}>
 {date&&<><button className="opsDayNumber" aria-label={date+' 선택'} onClick={()=>setDay(date)}>{Number(date.slice(-2))}</button><button className="opsDayAdd" aria-label={date+' 일정 등록'} onClick={()=>{setDay(date);setEditing({type:'aude-appointment',start:date+'T19:00'});}}>＋</button>{appointmentsForDay(date).map(r=><button key={r.id} className={'opsCalendarEvent '+(r.data.status==='취소'?'cancelled':'')} onClick={()=>setDetail(r)}><small>{seoulLocal(r.data.startAt!).slice(11)} · {r.data.status}</small><b>{r.data.clientName}</b><span>{r.data.kind}</span></button>)}</>}
 </div>)}</div>:<div className="opsAgenda">{shownDays.map(date=><section key={date}><h2>{date} <small>{weekdays[new Date(date+'T00:00:00Z').getUTCDay()]}</small></h2>{appointmentsForDay(date).length?appointmentsForDay(date).map(r=><button className="opsAgendaItem" key={r.id} onClick={()=>setDetail(r)}><strong>{seoulLocal(r.data.startAt!).slice(11)}</strong><span>{r.data.clientName} · {r.data.kind}<small>{r.data.duration}분 · {r.data.status}</small></span></button>):<p className="opsMuted">등록된 일정이 없습니다.</p>}</section>)}</div>}
 {calendarView==='month'&&<section className="opsSelectedDay"><h2>{day} 일정</h2>{appointmentsForDay(day).length?appointmentsForDay(day).map(r=><button className="opsAgendaItem" key={r.id} onClick={()=>setDetail(r)}><strong>{seoulLocal(r.data.startAt!).slice(11)}</strong><span>{r.data.clientName} · {r.data.kind}<small>{r.data.duration}분 · {r.data.status}</small></span></button>):<p>날짜 칸의 ＋ 버튼으로 일정을 등록하세요.</p>}</section>}</>:<>
 <div className="opsToolbar"><div className="opsTabs"><button className={tab==='charges'?'active':''} onClick={()=>{setTab('charges');setFilter('전체');}}>수납 관리</button><button className={tab==='expenses'?'active':''} onClick={()=>setTab('expenses')}>지출 관리</button></div><input aria-label="운영 기록 검색" placeholder="이름·항목 검색" value={query} onChange={e=>setQuery(e.target.value)}/></div>
 {tab==='charges'?<><div className="opsFilters">{['전체','미수납','일부 수납','수납 완료','환불','취소'].map(v=><button key={v} className={filter===v?'active':''} onClick={()=>setFilter(v)}>{v}</button>)}</div><p className="opsMuted">결제 항목은 전체 기간을 표시합니다. 위 금액은 선택한 월 기준이며, 미수납은 전체 기간 기준입니다.</p><div className="opsTableWrap"><table className="opsTable"><thead><tr><th>내담자·항목</th><th>받을 금액</th><th>보유 금액</th><th>미수납</th><th>상태</th></tr></thead><tbody>{chargeList.map(r=>{const t=chargeTotals(r.data);return <tr key={r.id}><td><button className="opsTextButton" onClick={()=>setDetail(r)}><b>{r.data.clientName}</b><span>{r.data.title}</span><small>{r.data.date}</small></button></td><td>{won(r.data.amount||0)}</td><td>{won(t.net)}{t.refunded>0&&<small>환불 {won(t.refunded)}</small>}</td><td>{won(t.due)}</td><td><span className="opsBadge">{chargeStatus(r.data)}</span></td></tr>;})}</tbody></table>{!chargeList.length&&<p className="opsEmpty">결제 항목을 등록한 뒤 입금·환불을 기록해 주세요.</p>}</div></>:<><p className="opsMuted">선택한 월의 지출을 표시합니다. 증빙 파일을 첨부하고 필요할 때 내려받을 수 있습니다.</p><div className="opsTableWrap"><table className="opsTable"><thead><tr><th>날짜</th><th>항목</th><th>분류</th><th>금액</th><th>증빙·상태</th></tr></thead><tbody>{expenseList.map(r=><tr key={r.id}><td>{r.data.date}</td><td><button className="opsTextButton" onClick={()=>setDetail(r)}>{r.data.title}</button></td><td>{r.data.category}</td><td>{won(r.data.amount||0)}</td><td>{r.data.attachments?.length||0}개 · {r.data.archived?'취소':'유효'}</td></tr>)}</tbody></table>{!expenseList.length&&<p className="opsEmpty">이번 달 지출을 등록해 주세요.</p>}</div></>}
 <p className="opsMuted">현금영수증 등 증빙의 실제 발급은 사용하는 발급 시스템에서 진행하고, 여기에는 처리 여부를 기록합니다.</p></>}
 </>}
 </section>
 {editing&&<OperationForm key={editing.row?.id||editing.type+editing.start} type={editing.type} row={editing.row} start={editing.start} clients={clients} defaultClient={clientFilter} data={data} onClose={()=>setEditing(null)} onSaved={r=>{replace(r);setEditing(null);setDetail(r);setNotice('기록을 저장했습니다.');}}/>}
 {detail&&!editing&&<OperationDetail row={detail} data={data} busy={busy} onClose={()=>setDetail(null)} onEdit={()=>setEditing({type:detail.data.type,row:detail})} onAction={(action,fields)=>mutate(detail,action,fields)} onUpdated={replace}/>}
 </main>;
}
function Dialog({title,children,onClose}:{title:string;children:React.ReactNode;onClose:()=>void}){const closeRef=useRef(onClose);closeRef.current=onClose;useEffect(()=>{const previous=document.activeElement as HTMLElement|null;const dialog=document.querySelector('.opsDialog') as HTMLElement|null;dialog?.querySelector<HTMLButtonElement>('button')?.focus();const key=(e:KeyboardEvent)=>{if(e.key==='Escape'){e.preventDefault();closeRef.current();}if(e.key==='Tab'&&dialog){const nodes=Array.from(dialog.querySelectorAll<HTMLElement>('button:not(:disabled),input:not(:disabled),select:not(:disabled),textarea:not(:disabled),a[href]'));if(!nodes.length)return;const first=nodes[0],last=nodes[nodes.length-1];if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus();}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus();}}};document.addEventListener('keydown',key);const overflow=document.body.style.overflow;document.body.style.overflow='hidden';return()=>{document.removeEventListener('keydown',key);document.body.style.overflow=overflow;previous?.focus();};},[]);return <div className="opsBackdrop"><section className="opsDialog" role="dialog" aria-modal="true" aria-label={title}><div className="opsDialogHeading"><h2>{title}</h2><button aria-label="닫기" onClick={onClose}>×</button></div>{children}</section></div>;}
function OperationForm({type,row,start,clients,defaultClient,data,onClose,onSaved}:{type:OperationType;row?:OperationRow;start?:string;clients:Client[];defaultClient:string;data:Operations;onClose:()=>void;onSaved:(r:OperationRow)=>void}){
 const initial={clientId:row?.data.clientId||defaultClient,title:row?.data.title||(type==='aude-appointment'?'개인상담':''),memo:row?.data.memo||'',startAt:row?.data.startAt?seoulLocal(row.data.startAt):start||seoulDate()+'T19:00',duration:row?.data.duration||60,kind:row?.data.kind||'개인상담',status:row?.data.status||'예약',chargeId:row?.data.chargeId||'',date:row?.data.date||seoulDate(),amount:row?.data.amount??(type==='aude-charge'?100000:0),category:row?.data.category||'기타'};
 const [form,setForm]=useState(initial);const [requestId]=useState(()=>crypto.randomUUID());const [busy,setBusy]=useState(false);const [error,setError]=useState('');const dirty=JSON.stringify(form)!==JSON.stringify(initial);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 function close(){if(!busy&&(!dirty||confirm('저장하지 않은 입력을 버릴까요?')))onClose();}
 function change(key:string,value:string|number){setForm(f=>({...f,[key]:value}));}
 const linkedCharges=data.charges.filter(r=>r.data.clientId===form.clientId&&(!r.data.archived||r.id===row?.data.chargeId));
 async function submit(e:FormEvent){e.preventDefault();if(busy)return;setError('');if(type==='aude-appointment'){const proposed={...form,type,startAt:new Date(form.startAt+':00+09:00').toISOString()} as unknown as OperationRow['data'];const conflicts=data.appointments.filter(r=>r.id!==row?.id&&overlaps(proposed,r.data));if(conflicts.length&&!confirm(`같은 시간에 ${conflicts.length}개 예약이 있습니다. 시간을 겹쳐 등록할까요?`))return;}setBusy(true);try{const saved=await api(row?'PATCH':'POST',{type,requestId,...(row?{id:row.id,version:row.data.version,action:'edit'}:{}),...form});onSaved(saved);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 return <Dialog title={(row?'수정 · ':'등록 · ')+(type==='aude-appointment'?'상담 일정':type==='aude-charge'?'결제 항목':'지출')} onClose={close}><form className="opsForm" onSubmit={submit}><fieldset disabled={busy}>
 {type!=='aude-expense'&&<label>내담자<select required value={form.clientId} disabled={!!row} onChange={e=>setForm(f=>({...f,clientId:e.target.value,chargeId:''}))}><option value="">내담자를 선택해 주세요</option>{clients.map(c=><option key={c.id} value={c.id}>{c.name} · {c.clientCode}</option>)}</select></label>}
 <label>항목<input required maxLength={120} value={form.title} onChange={e=>change('title',e.target.value)} placeholder={type==='aude-charge'?'예: 개인상담 1회 / 기본 성격검사 패키지':'항목 입력'}/></label>
 {type==='aude-appointment'?<><div className="opsFormGrid"><label>종류<select value={form.kind} onChange={e=>setForm(f=>({...f,kind:e.target.value,title:appointmentKinds.includes(f.title as never)?e.target.value:f.title}))}>{appointmentKinds.map(k=><option key={k}>{k}</option>)}</select></label><label>상태<select value={form.status} onChange={e=>change('status',e.target.value)}>{appointmentStatuses.map(k=><option key={k}>{k}</option>)}</select></label></div><div className="opsFormGrid"><label>날짜·시간 · 한국 시간<input required type="datetime-local" min="2000-01-01T00:00" max="2100-12-31T23:59" value={form.startAt} onChange={e=>change('startAt',e.target.value)}/></label><label>소요 시간 · 분<input required type="number" min={10} max={480} step={1} value={form.duration} onChange={e=>change('duration',Number(e.target.value))}/></label></div><label>연결할 결제 항목 · 선택<select value={form.chargeId} onChange={e=>change('chargeId',e.target.value)}><option value="">연결하지 않음</option>{linkedCharges.map(r=><option key={r.id} value={r.id}>{r.data.title} · {won(r.data.amount||0)} · {r.data.date}</option>)}</select></label><p className="opsMuted">검사 실시·해석상담을 같은 패키지 결제 항목에 연결할 수 있습니다.</p></>:<><div className="opsFormGrid"><label>{type==='aude-charge'?'결제 항목 등록일':'지출일'}<input required type="date" min="2000-01-01" max="2100-12-31" value={form.date} onChange={e=>change('date',e.target.value)}/></label><label>{type==='aude-charge'?'받을 금액':'지출 금액'} · 원<input required type="number" min={0} max={1000000000} step={1} value={form.amount} onChange={e=>change('amount',Number(e.target.value))}/></label></div>{type==='aude-expense'?<><label>분류<select value={form.category} onChange={e=>change('category',e.target.value)}>{expenseCategories.map(k=><option key={k}>{k}</option>)}</select></label><p className="opsMuted">저장 후 지출 상세 화면에서 영수증을 첨부할 수 있습니다.</p></>:<p className="opsMuted">받을 금액을 등록한 뒤, 상세 화면에서 실제 입금·환불을 기록하세요.</p>}</>}
 <label>메모<textarea rows={4} maxLength={2000} value={form.memo} onChange={e=>change('memo',e.target.value)}/></label></fieldset>{error&&<p className="opsError" role="alert">{error}</p>}<div className="opsFormActions"><button type="button" disabled={busy} onClick={close}>닫기</button><button className="opsPrimary" disabled={busy||!form.title.trim()||(type!=='aude-expense'&&!form.clientId)}>{busy?'저장 중…':'저장'}</button></div></form></Dialog>;
}
function OperationDetail({row,data,busy,onClose,onEdit,onAction,onUpdated}:{row:OperationRow;data:Operations;busy:boolean;onClose:()=>void;onEdit:()=>void;onAction:(action:string,fields?:object)=>Promise<void>;onUpdated:(r:OperationRow)=>void}){
 const d=row.data;const [payment,setPayment]=useState<'receipt'|'refund'|null>(null);const [uploadBusy,setUploadBusy]=useState(false);const [error,setError]=useState('');const [notice,setNotice]=useState('');const t=chargeTotals(d);
 function close(){if(!busy&&!uploadBusy&&(!payment||confirm('작성 중인 입출금 입력을 버리고 닫을까요?')))onClose();}
 async function act(action:string,fields:object={}){setError('');try{await onAction(action,fields);}catch(e){setError((e as Error).message);}}
 async function upload(file:File){if(uploadBusy)return;setUploadBusy(true);setError('');try{if(file.size>4194304)throw new Error('영수증은 4MB 이하로 첨부해 주세요.');const f=new FormData();f.set('id',row.id);f.set('file',file);const r=await fetch('/api/admin/receipts',{method:'POST',body:f}),result=await r.json();if(!r.ok)throw new Error(result.error);onUpdated(result);setNotice('영수증을 첨부했습니다.');}catch(e){setError((e as Error).message);}finally{setUploadBusy(false);}}
 return <Dialog title={d.title} onClose={close}><div className="opsDetail"><div className="opsDetailActions">{d.clientId&&<><Link href={'/admin/clients?client='+d.clientId}>내담자·회기·심리검사 기록 ↗</Link><Link href={'/admin/calendar?client='+d.clientId}>내담자 일정</Link><Link href={'/admin/finance?client='+d.clientId}>내담자 수납</Link></>}<button disabled={busy||uploadBusy} onClick={onEdit}>정보 수정</button></div>{error&&<p className="opsError" role="alert">{error}</p>}{notice&&<p role="status">{notice}</p>}
 {d.type==='aude-appointment'?<><dl><dt>내담자</dt><dd>{d.clientName}</dd><dt>일정</dt><dd>{seoulLocal(d.startAt!).replace('T',' ')} · {d.duration}분</dd><dt>종류·상태</dt><dd>{d.kind} · {d.status}</dd><dt>결제 항목</dt><dd>{data.charges.find(r=>r.id===d.chargeId)?.data.title||'연결하지 않음'}</dd></dl><p className="opsMuted">일정 완료와 회기 기록은 각각 저장합니다. 위 내담자 기록에서 상담 내용을 작성하세요.</p></>:d.type==='aude-charge'?<><dl><dt>내담자</dt><dd>{d.clientName}</dd><dt>받을 금액</dt><dd>{won(d.amount||0)}</dd><dt>누적 입금 / 환불</dt><dd>{won(t.received)} / {won(t.refunded)}</dd><dt>보유 금액 / 미수납</dt><dd>{won(t.net)} / {won(t.due)}</dd><dt>상태</dt><dd>{chargeStatus(d)}</dd></dl><p className="opsMuted">환불한 금액은 미수납에 다시 더하지 않습니다.</p><div className="opsDetailActions"><button className="opsPrimary" disabled={busy||d.archived||t.due===0} onClick={()=>setPayment('receipt')}>입금 기록</button><button disabled={busy||d.archived||t.net===0} onClick={()=>setPayment('refund')}>환불 기록</button></div>
 {payment&&<PaymentForm key={payment+row.id} row={row} direction={payment} onClose={()=>setPayment(null)} onSaved={r=>{onUpdated(r);setPayment(null);setNotice('입출금 기록을 저장했습니다.');}}/>}
 <h3>입출금 이력</h3>{!d.payments?.length&&<p className="opsMuted">아직 입출금 기록이 없습니다.</p>}{(d.payments||[]).map(p=><div key={p.id} className={'opsPayment '+(p.voided?'voided':'')}><div><strong>{p.direction==='receipt'?'입금':'환불'} · {won(p.amount)}</strong><small>{p.date} · {p.method}{p.voided?' · 정정됨 (집계 제외)':''}</small><p>{p.memo}</p></div>{!p.voided&&<div><label>증빙 처리<select aria-label={p.date+' '+p.amount+'원 증빙 처리'} disabled={busy} value={p.evidence} onChange={e=>void act('evidence',{paymentId:p.id,evidence:e.target.value})}>{evidenceStatuses.map(s=><option key={s}>{s}</option>)}</select></label><button disabled={busy} onClick={()=>{if(confirm('잘못 입력한 입출금 기록을 정정할까요? 이력은 남고 집계에서 제외됩니다.'))void act('void-payment',{paymentId:p.id});}}>오입력 정정</button></div>}</div>)}
 <h3>연결된 일정</h3>{data.appointments.filter(a=>a.data.chargeId===row.id).map(a=><p key={a.id}>{seoulLocal(a.data.startAt!).replace('T',' ')} · {a.data.kind} · {a.data.status}</p>)}
 </>:<><dl><dt>날짜·분류</dt><dd>{d.date} · {d.category}</dd><dt>지출 금액</dt><dd>{won(d.amount||0)}</dd><dt>상태</dt><dd>{d.archived?'취소 (집계 제외)':'유효'}</dd></dl><h3>영수증</h3><p className="opsMuted">PDF·JPG·PNG·WebP, 파일당 최대 4MB. 관리자만 내려받을 수 있습니다.</p>{(d.attachments||[]).map(a=><a className="opsAttachment" key={a.id} href={`/api/admin/receipts?id=${row.id}&attachment=${a.id}`}>{a.name} ↓ <small>{Math.ceil(a.size/1024)}KB</small></a>)}{!d.archived&&<label className="opsUpload">{uploadBusy?'첨부 중…':'영수증 첨부'}<input type="file" accept="application/pdf,image/jpeg,image/png,image/webp" disabled={busy||uploadBusy||(d.attachments?.length||0)>=10} onChange={e=>{const file=e.target.files?.[0];if(file)void upload(file);e.target.value='';}}/></label>}</>}
 {d.memo&&<div className="opsMemo"><h3>메모</h3><p>{d.memo}</p></div>}{d.type!=='aude-appointment'&&<button className="opsDanger" disabled={busy||uploadBusy} onClick={()=>{if(confirm(d.archived?'취소된 기록을 복원할까요?':'이 항목을 취소 처리할까요? 기록은 보존되고 집계에서 제외됩니다.'))void act('archive',{archived:!d.archived});}}>{d.archived?'취소 복원':'항목 취소'}</button>}
 </div></Dialog>;
}
function PaymentForm({row,direction,onClose,onSaved}:{row:OperationRow;direction:'receipt'|'refund';onClose:()=>void;onSaved:(r:OperationRow)=>void}){const t=chargeTotals(row.data);const [form,setForm]=useState({date:seoulDate(),amount:direction==='receipt'?t.due:t.net,method:'계좌이체',evidence:'확인 필요',memo:''});const [paymentId]=useState(()=>crypto.randomUUID());const [busy,setBusy]=useState(false);const [error,setError]=useState('');async function submit(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');try{onSaved(await api('PATCH',{id:row.id,version:row.data.version,action:'payment',paymentId,direction,...form}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}return <form className="opsPaymentForm opsForm" onSubmit={submit}><h3>{direction==='receipt'?'입금':'환불'} 기록</h3><fieldset disabled={busy}><div className="opsFormGrid"><label>날짜<input required type="date" min="2000-01-01" max="2100-12-31" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))}/></label><label>금액 · 원<input required type="number" min={1} max={direction==='receipt'?t.due:t.net} step={1} value={form.amount} onChange={e=>setForm(f=>({...f,amount:Number(e.target.value)}))}/></label><label>방법<select value={form.method} onChange={e=>setForm(f=>({...f,method:e.target.value}))}>{paymentMethods.map(v=><option key={v}>{v}</option>)}</select></label><label>증빙 처리<select value={form.evidence} onChange={e=>setForm(f=>({...f,evidence:e.target.value}))}>{evidenceStatuses.map(v=><option key={v}>{v}</option>)}</select></label></div><label>메모<input maxLength={1000} value={form.memo} onChange={e=>setForm(f=>({...f,memo:e.target.value}))}/></label></fieldset>{error&&<p className="opsError" role="alert">{error}</p>}<div className="opsFormActions"><button type="button" disabled={busy} onClick={onClose}>닫기</button><button disabled={busy} className="opsPrimary">{busy?'저장 중…':'저장'}</button></div></form>;}
