import { randomUUID } from 'node:crypto';
import { NextResponse } from 'next/server';
import { admin,error,privateHeaders,validId } from '../../../lib/tat';
import { getOperation,getOperations,validateOperation,insertOperation,updateOperation,addPayment } from '../../../lib/operations';
import { Operation,OperationType,chargeTotals,seoulDate } from '../../../lib/operations-model';
export const runtime='nodejs';
export async function GET(){if(!await admin())return NextResponse.json({error:'관리자 로그인이 필요합니다.'},{status:401});try{const rows=await getOperations();return NextResponse.json({appointments:rows.filter(r=>r.data.type==='aude-appointment'),charges:rows.filter(r=>r.data.type==='aude-charge'),expenses:rows.filter(r=>r.data.type==='aude-expense')},{headers:privateHeaders});}catch(e){return NextResponse.json({error:error(e)},{status:400});}}
function appointmentChargeNonce(nonce:string){return nonce.slice(0,-1)+(nonce.endsWith('0')?'1':'0');}
function appointmentChargeFields(fields:Partial<Operation>){return {clientId:fields.clientId,clientName:fields.clientName,title:fields.title||'상담 일정',memo:fields.memo||'',date:seoulDate(fields.startAt!),amount:fields.amount||0,archived:fields.status==='취소'};}
async function syncAppointmentCharge(next:Operation){if(next.type!=='aude-appointment')return next;let charge;if(next.chargeId)charge=await getOperation(next.chargeId);else{charge=await insertOperation('aude-charge',appointmentChargeFields(next),randomUUID());next={...next,chargeId:charge.id};}if(charge.data.type!=='aude-charge')throw new Error('연결된 수납 항목을 확인해 주세요.');if(next.status==='취소'&&chargeTotals(charge.data).net>0)throw new Error('이미 수납된 일정입니다. 먼저 수납 화면에서 환불을 기록한 뒤 일정을 취소해 주세요.');const synced={...charge.data,...appointmentChargeFields(next),archived:next.status==='취소'};if(synced.amount!==(charge.data.amount||0)||synced.title!==charge.data.title||synced.date!==charge.data.date||synced.memo!==charge.data.memo||synced.archived!==charge.data.archived)await updateOperation(charge,synced);return next;}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:'관리자 로그인이 필요합니다.'},{status:401});try{const i=await request.json();if(!validId(i.requestId))throw new Error('저장 요청을 확인해 주세요.');const type=i.type as OperationType;let fields=await validateOperation(type,i);if(type==='aude-appointment'){const charge=await insertOperation('aude-charge',appointmentChargeFields(fields),appointmentChargeNonce(i.requestId));fields={...fields,chargeId:charge.id};}return NextResponse.json(await insertOperation(type,fields,i.requestId),{headers:privateHeaders});}catch(e){return NextResponse.json({error:error(e)},{status:400});}}
export async function PATCH(request:Request){if(!await admin())return NextResponse.json({error:'관리자 로그인이 필요합니다.'},{status:401});try{const i=await request.json(),row=await getOperation(i.id);if(i.action==='payment'&&row.data.payments?.some(p=>p.id===i.paymentId))return NextResponse.json(row,{headers:privateHeaders});if(i.version!==row.data.version)throw new Error('다른 변경사항이 저장되었습니다. 기록을 다시 열고 시도해 주세요.');let data=row.data;
 if(i.action==='payment')data=addPayment(data,i);
 else if(i.action==='void-payment'){if(data.type!=='aude-charge')throw new Error('결제 항목을 확인해 주세요.');const p=data.payments?.find(p=>p.id===i.paymentId);if(!p)throw new Error('입출금 기록을 찾지 못했습니다.');data={...data,payments:data.payments!.map(p=>p.id===i.paymentId?{...p,voided:true}:p)};if(chargeTotals(data).net<0)throw new Error('연결된 환불 기록을 먼저 정정해 주세요.');}
 else if(i.action==='evidence'){if(data.type!=='aude-charge'||!['확인 필요','처리 완료','해당 없음'].includes(i.evidence)||!data.payments?.some(p=>p.id===i.paymentId))throw new Error('증빙 상태를 확인해 주세요.');data={...data,payments:data.payments!.map(p=>p.id===i.paymentId?{...p,evidence:i.evidence}:p)};}
 else if(i.action==='archive'){if(data.type==='aude-appointment')throw new Error('일정 상태를 취소로 변경해 주세요.');if(data.type==='aude-charge'&&chargeTotals(data).net>0)throw new Error('수납 금액을 환불한 뒤 결제 항목을 취소해 주세요.');if(typeof i.archived!=='boolean')throw new Error('취소 상태를 확인해 주세요.');data={...data,archived:i.archived};}
 else if(i.action==='edit'){data={...data,...await validateOperation(data.type,i,data)};data=await syncAppointmentCharge(data);}
 else throw new Error('요청을 확인해 주세요.');return NextResponse.json(await updateOperation(row,data),{headers:privateHeaders});}catch(e){return NextResponse.json({error:error(e)},{status:400});}}
