'use client';
import { useEffect,useState } from 'react';
import type { TatRow } from '../../lib/tat';
import { CardRecord,CardRecords,RecordChange,RecordField,ImportedRecord,fieldLabels,fieldLimits,recordFields,parseRecordImport } from '../../lib/tat-records';
import './tat-records.css';
type Props={session:TatRow;onSaved:(row:TatRow)=>void;onDirty:(dirty:boolean)=>void};
export default function TatRecordEditor({session,onSaved,onDirty}:Props){
 const [draft,setDraft]=useState<CardRecords>(()=>structuredClone(session.data.cardRecords||{}));
 const [base,setBase]=useState<CardRecords>(()=>structuredClone(session.data.cardRecords||{}));
 const [summary,setSummary]=useState(session.data.summary||'');const [baseSummary,setBaseSummary]=useState(session.data.summary||'');
 const [expanded,setExpanded]=useState(!!session.data.endedAt);const [selected,setSelected]=useState(session.data.order[0]);
 const [paste,setPaste]=useState('');const [importOpen,setImportOpen]=useState(false);const [preview,setPreview]=useState<ImportedRecord[]>([]);const [selectedCells,setSelectedCells]=useState<Set<string>>(new Set());
 const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');
 const changes:RecordChange[]=session.data.order.flatMap(card=>{const fields:CardRecord={},expected:CardRecord={};for(const f of recordFields){if((draft[card]?.[f]||'')!==(base[card]?.[f]||'')){fields[f]=draft[card]?.[f]||'';expected[f]=base[card]?.[f]||'';}}return Object.keys(fields).length?[{card,fields,expected}]:[];});
 const dirty=changes.length>0||summary!==baseSummary;
 useEffect(()=>{onDirty(dirty);},[dirty,onDirty]);
 useEffect(()=>{if(!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[dirty]);
 useEffect(()=>{if(session.data.endedAt)setExpanded(true);},[session.data.endedAt]);
 const current=expanded?selected:session.data.order[session.data.index];const record=draft[current]||{};
 function change(card:string,field:RecordField,value:string){setDraft(x=>({...x,[card]:{...x[card],[field]:value}}));setMessage('');setPreview([]);}
 async function save(){if(busy||!dirty)return;setBusy(true);setError('');setMessage('');try{const r=await fetch('/api/admin/tat',{method:'PATCH',headers:{'Content-Type':'application/json'},body:JSON.stringify({id:session.id,action:'records',changes,...(summary!==baseSummary?{summary,expectedSummary:baseSummary}:{})})});const row=await r.json();if(!r.ok)throw new Error(row.error||'저장하지 못했습니다.');setBase(structuredClone(row.data.cardRecords||{}));setDraft(structuredClone(row.data.cardRecords||{}));setBaseSummary(row.data.summary||'');setSummary(row.data.summary||'');onSaved(row);setMessage('도판 기록과 해석을 저장했습니다.');}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function inspect(){setError('');try{const rows=parseRecordImport(paste,session.data.order);if(!rows.length)throw new Error('가져올 도판이 없습니다.');setPreview(rows);setSelectedCells(new Set(rows.flatMap(r=>Object.entries(r.fields).filter(([f,v])=>!!v&&!(draft[r.card]?.[f as RecordField]||'')).map(([f])=>r.card+':'+f))));}catch(e){setError((e as Error).message);setPreview([]);}}
 function apply(){if(!selectedCells.size)return;setDraft(old=>{const next=structuredClone(old);for(const r of preview)for(const [f,value]of Object.entries(r.fields))if(selectedCells.has(r.card+':'+f))next[r.card]={...next[r.card],[f]:value};return next;});setPreview([]);setImportOpen(false);setPaste('');setExpanded(true);setMessage('가져온 내용을 편집 화면에 적용했습니다. 기록 저장을 눌러 완료해 주세요.');}
 function toggle(key:string){setSelectedCells(x=>{const next=new Set(x);next.has(key)?next.delete(key):next.add(key);return next;});}
 function copyTsv(){const q=(v:string)=>/[\t\r\n"]/.test(v)?'"'+v.replaceAll('"','""')+'"':v;const fields:RecordField[]=['story','hero','need','pressure','interpretation','note'];const rows=[['도판 번호',...fields.map(f=>fieldLabels[f])],...session.data.order.map(card=>[card,...fields.map(f=>draft[card]?.[f]||'')])];void navigator.clipboard.writeText(rows.map(r=>r.map(q).join('\t')).join('\n')).then(()=>setMessage('현재 편집 내용을 복사했습니다. 엑셀에 붙여넣을 수 있습니다.'),()=>setError('복사하지 못했습니다. 브라우저의 클립보드 권한을 확인해 주세요.'));}
 return <section className="tatPanel tatRecordEditor" aria-label="검사 기록·해석"><div className="tatRow"><h2>{expanded?'검사 기록·해석':'도판별 실시 메모'}</h2><button type="button" onClick={()=>{if(!expanded)setSelected(session.data.order[session.data.index]);setExpanded(!expanded);}}>{expanded?'실시 메모로 돌아가기':'검사 기록·해석 열기'}</button></div><p>관리자에게만 표시됩니다. 도판을 바꿔도 작성 중인 내용이 유지됩니다.</p>
 {expanded&&<><div className="tatRow"><button disabled={busy} onClick={()=>{setImportOpen(!importOpen);setPreview([]);}}>여러 도판 한 번에 가져오기</button><button onClick={copyTsv}>엑셀로 복사</button></div><nav className="tatRecordTabs" aria-label="기록할 도판">{session.data.order.map(card=><button key={card} aria-pressed={current===card} className={current===card?'tatPrimary':''} onClick={()=>setSelected(card)}>{card}{Object.values(draft[card]||{}).some(Boolean)&&<span aria-label="기록 있음"> ·</span>}</button>)}</nav></>}
 <h3>{current} 도판</h3><label className="tatLabel">실시 메모<textarea disabled={busy} rows={4} value={record.note||''} maxLength={fieldLimits.note} onChange={e=>change(current,'note',e.target.value)} placeholder="반응 시간, 행동 관찰, 추가 질문 등을 기록하세요."/></label>
 {expanded&&<><label className="tatLabel">이야기 원문<textarea disabled={busy} rows={12} value={record.story||''} maxLength={fieldLimits.story} onChange={e=>change(current,'story',e.target.value)} placeholder="내담자의 이야기를 그대로 입력하거나 붙여넣으세요."/></label><div className="tatInterpretationGrid">{(['hero','need','pressure','interpretation'] as RecordField[]).map(f=><label className={'tatLabel '+(f==='interpretation'?'wide':'')} key={f}>{fieldLabels[f]}<textarea disabled={busy} rows={f==='interpretation'?6:3} value={record[f]||''} maxLength={fieldLimits[f]} onChange={e=>change(current,f,e.target.value)}/></label>)}</div><label className="tatLabel tatSummary">종합 해석<textarea disabled={busy} rows={6} value={summary} maxLength={30000} onChange={e=>setSummary(e.target.value)} placeholder="전체 도판의 공통 주제와 추가로 확인할 내용을 정리하세요."/></label></>}
 {session.data.note&&<details className="tatLegacyNote"><summary>이전 검사 전체 메모</summary><p>{session.data.note}</p></details>}
 {error&&<p className="tatError" role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<div className="tatRecordSave"><span>{dirty?'저장하지 않은 변경사항이 있습니다.':'저장된 기록과 같습니다.'}</span><button className="tatPrimary" disabled={busy||!dirty} onClick={save}>{busy?'저장 중…':'기록 저장'}</button></div>
 {importOpen&&<section className="tatImport" aria-label="엑셀 기록 가져오기"><h3>여러 도판 한 번에 가져오기</h3><p>엑셀의 표를 복사해 아래에 붙여넣으세요. 첫 행에 열 제목이 있으면 원하는 항목만 가져올 수도 있습니다.</p><p className="tatColumnGuide">도판 번호 → 이야기 원문 → 주인공 → 욕구 → 압력 → 해석</p><p>예: 1, 2, 3BM. 이 검사에 선택된 도판만 가져올 수 있습니다. 셀 안 줄바꿈도 유지됩니다.</p><textarea rows={8} disabled={busy} value={paste} onChange={e=>{setPaste(e.target.value);setPreview([]);}} placeholder="엑셀에서 복사한 표를 여기에 붙여넣으세요." aria-label="엑셀 표 붙여넣기"/><div className="tatRow"><button disabled={busy||!paste.trim()} onClick={inspect}>미리보기</button><button onClick={()=>{setImportOpen(false);setPreview([]);}}>닫기</button></div>
 {preview.length>0&&<><p>빈 항목은 기본으로 선택됩니다. 기존 내용이 있는 항목은 확인 후 체크하면 덮어씁니다. 빈 셀을 체크하면 기존 내용이 삭제됩니다.</p><div className="tatImportTableWrap"><table className="tatImportTable"><thead><tr><th>도판</th><th>항목</th><th>기존 내용</th><th>가져올 내용</th></tr></thead><tbody>{preview.flatMap(r=>Object.entries(r.fields).map(([f,value])=><tr key={r.card+':'+f}><th>{r.card}</th><td><label><input type="checkbox" checked={selectedCells.has(r.card+':'+f)} onChange={()=>toggle(r.card+':'+f)}/>{fieldLabels[f as RecordField]}</label></td><td>{draft[r.card]?.[f as RecordField]||'—'}</td><td>{value||'빈 셀'}</td></tr>))}</tbody></table></div><div className="tatRow"><button onClick={()=>setSelectedCells(new Set(preview.flatMap(r=>Object.keys(r.fields).map(f=>r.card+':'+f))))}>모든 항목 선택</button><button onClick={()=>setSelectedCells(new Set())}>선택 해제</button><button className="tatPrimary" disabled={!selectedCells.size||busy} onClick={apply}>선택한 {selectedCells.size}개 항목 적용</button></div></>}
 </section>}
 </section>;
}
