import { NextResponse } from 'next/server';
import { admin,error,privateHeaders,validId } from '../../../lib/tat';
import { supabaseAdminRequest } from '../../../lib/supabase';
import { getOperation,updateOperation } from '../../../lib/operations';
const bucket='aude-expense-receipts-private';export const runtime='nodejs';
async function ensureBucket(){const r=await supabaseAdminRequest('/storage/v1/bucket');const b=(await r.json()).find((b:{id:string})=>b.id===bucket);if(b){if(b.public)throw new Error('영수증 저장소의 비공개 설정을 확인해 주세요.');return;}try{await supabaseAdminRequest('/storage/v1/bucket',{method:'POST',body:JSON.stringify({id:bucket,name:bucket,public:false,file_size_limit:4194304,allowed_mime_types:['application/pdf','image/jpeg','image/png','image/webp']})});}catch(e){const check=await supabaseAdminRequest('/storage/v1/bucket');if(!(await check.json()).some((b:{id:string;public:boolean})=>b.id===bucket&&!b.public))throw e;}}
export async function POST(request:Request){if(!await admin())return NextResponse.json({error:'Unauthorized'},{status:401});try{const f=await request.formData(),id=String(f.get('id')||''),file=f.get('file');let row=await getOperation(id);if(row.data.type!=='aude-expense'||row.data.archived)throw new Error('유효한 지출 기록을 선택해 주세요.');if(!(file instanceof File)||!file.size||file.size>4194304)throw new Error('영수증은 4MB 이하로 첨부해 주세요.');if((row.data.attachments||[]).length>=10)throw new Error('영수증은 지출별 최대 10개까지 첨부할 수 있습니다.');const bytes=new Uint8Array(await file.arrayBuffer());let mime='';if(bytes[0]===0xff&&bytes[1]===0xd8&&bytes[2]===0xff)mime='image/jpeg';else if(Buffer.from(bytes.slice(0,8)).equals(Buffer.from([137,80,78,71,13,10,26,10])))mime='image/png';else if(Buffer.from(bytes.slice(0,5)).toString()==='%PDF-')mime='application/pdf';else if(Buffer.from(bytes.slice(0,4)).toString()==='RIFF'&&Buffer.from(bytes.slice(8,12)).toString()==='WEBP')mime='image/webp';if(!mime)throw new Error('PDF·JPG·PNG·WebP 영수증을 첨부해 주세요.');await ensureBucket();const attachment={id:crypto.randomUUID(),name:file.name.slice(0,160),mime,size:file.size};await supabaseAdminRequest(`/storage/v1/object/${bucket}/${id}/${attachment.id}`,{method:'POST',headers:{'Content-Type':mime},body:bytes});
 for(let n=0;n<5;n++){row=await getOperation(id);if(row.data.archived)throw new Error('취소된 지출입니다.');if((row.data.attachments||[]).length>=10)throw new Error('최대 첨부 수를 초과했습니다.');try{return NextResponse.json(await updateOperation(row,{...row.data,attachments:[...(row.data.attachments||[]),attachment]}),{headers:privateHeaders});}catch(e){if(n===4||!(e instanceof Error)||!e.message.startsWith('다른 변경사항'))throw e;}}
 throw new Error('영수증을 저장하지 못했습니다.');}catch(e){return NextResponse.json({error:error(e)},{status:400});}}
export async function GET(request:Request){if(!await admin())return NextResponse.json({error:'Unauthorized'},{status:401});try{const p=new URL(request.url).searchParams,row=await getOperation(p.get('id')||''),attachment=row.data.attachments?.find(a=>a.id===p.get('attachment'));if(row.data.type!=='aude-expense'||!attachment||!validId(attachment.id))throw new Error('영수증을 찾지 못했습니다.');const r=await supabaseAdminRequest(`/storage/v1/object/authenticated/${bucket}/${row.id}/${attachment.id}`);return new Response(r.body,{headers:{...privateHeaders,'Content-Type':attachment.mime,'Content-Disposition':"attachment; filename*=UTF-8''"+encodeURIComponent(attachment.name)}});}catch(e){return NextResponse.json({error:error(e)},{status:400});}}
